### PR TITLE
Other modal dialogues don't work when Monograph drop down is displayed

### LINKED ISSUE #1730: Other modal dialogues don't work when Monograph drop down is displayed
1. Make a note and publish it
2. Click the "Published" drop down on the top right
3. Leave it open
4. Try to do something else such as clicking "Report an issue" or Settings>Notesnook Importer>Import from Zip file> How do I get the zip file?

It doesn't work.

**Device information:**
App version: 2.4.0-9e382b1-web
OS: Linux 64-bit
Browser: Firefox 109.0
Pro: true

### PR DESCRIPTION
**Pull request by gitstart**
Fixes #1730 
Added an overlay to interface when a modal is opened so it does not seem like other modals are accessible.

https://user-images.githubusercontent.com/1501599/216994658-048d7642-ccc7-4062-846d-f4376e5d0e40.mp4

### CODE REVIEW

**Comment by thecodrr** [comment]
Hey, thanks for the PR! I'll take a look at it ASAP and review.

**Comment by thecodrr** [comment]
>  Added an overlay to interface when a modal is opened so it does not seem like other modals are accessible.

That's the whole point behind opening it in a corner, though. The publish popup is not a modal intentionally. Secondly, I wasn't able to reproduce the #1730 in the latest version anyway.

What would be good UX-wise would be auto close the publish popup when the user clicks away.

**Comment by gitstart** [comment]
@thecodrr thank you for the review, so what I can summarise from it is that we dont need the overlay anymore? Just need to implement `auto close the publish popup when the user clicks away`?

**Comment by thecodrr** [comment]
Yes.

**Comment by gitstart** [comment]
Thank you for clarification, a fix should be coming your way soon.

**Comment by gitstart** [comment]
Hello @thecodrr, the changes you suggested have been implemented.

**Comment by thecodrr** [comment]
Hey, the `Signed-off by:` line should be on its own. Like this:

image

Please note that you also have to use your real name; anonymous names like Gitstart are not accepted. This is for legal purposes because your contribution is affiliated with you; under your name.

Hope you understand.

**Comment by thecodrr** [comment]
Closing this due to invalid `Signed-off by` header.

**Pull request closed without merging**
