### PR TITLE
Clicking on Settings doesn't toggle the settings pane on/off

### LINKED ISSUE #1750: Clicking on Settings doesn't toggle the settings pane on/off
If I click the Settings button once, it opens as expected. But when Settings pane is open, if I click on Settings button again I am expecting it to close but it does not happen. I have to click on some other tab like Notes, Notebooks and click on same twice to make that pane disappear which appears to be an overkill just to close the settings pane.

**Device information:**
App version: 2.4.0-e426d9d-desktop
OS: Windows 10 64-bit
Browser: Electron 21.1.1
Pro: true

### PR DESCRIPTION
**Pull request by gitstart**
As the problem is still there when toggling the setting panel.
This fixes the problem and settings pane is now working as expected.

Fixes #1750 

https://user-images.githubusercontent.com/1501599/217262630-b2fee23b-887d-49f6-9479-c1803ffeb41c.mp4

### CODE REVIEW

**Comment by thecodrr** [comment]
Hi, thanks for the PR.

I see that you haven't followed the commit guidelines detailed in [our contributing guidelines](https://github.com/streetwriters/notesnook/blob/master/CONTRIBUTING.md#commit-guidelines). Please sign off your commits using your full name.

**Comment by gitstart** [comment]
Apologies for that, I think it should be fixed now.

**Comment by thecodrr** [comment]
@gitstart The commits are still not signed off.

**Comment by thecodrr** [comment]
Thanks!

**Pull request merged**
