### PR TITLE
editor: improved use-editor.ts hook 

### LINKED ISSUE #2086: Changing editor settings requires app restart to take effect
Turning off double-spaced lines does not hold til next app start. Very frustrating!

**Device information:**
App version: 2.4.4-2c6f205-web
OS: Windows 10 64-bit
Browser: Microsoft Edge 110.0.1587.63
Pro: true

### PR DESCRIPTION
**Pull request by Abdulrehman-Jafer**
Issue: Changing editor settings requires app restart to take effect #2086
web:  Also added doubelSpacedLines in the dependencies of useTipTap  and also in the settings edited restart editor message to New settings are applied!

Closes #2086

### CODE REVIEW

**Comment by thecodrr** [comment]
@Abdulrehman-Jafer after some testing I realized that this behavior is web/desktop specific i.e. mobile doesn't have this issue so can we fix it on the web side instead?

**Comment by Abdulrehman-Jafer** [comment]
Ok I'll look into it but this problem is also in mob

**Comment by Abdulrehman-Jafer** [comment]
And secondly this new settings is not only for double space I mean it prevent any loss of data if we add anything in editor dependency to reset the editor what do you think about it?

**Comment by thecodrr** [comment]
@Abdulrehman-Jafer I tested it on mobile and it is working without these changes. Just had to add `doubleSpacedLines` in the dependency array.

Let's move this to the web side of the app instead of in the editor.

**Pull request closed without merging**
